version: '3.4'

services:
  api:
    volumes:
      - ./app:/srv
    environment:
      - FLASK_DEBUG=1
      - PYTHON_ENV=development
    ports:
      - "${APP_PORT}:5000"

  front:
    volumes:
      - ./front:/srv
    command: npm start
    ports:
      - "${FRONT_PORT}:8080"

  web:
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./front/dist:/public/onikuflow
    ports:
      - ${WEB_PORT}:80

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

