version: '3.4'

volumes: 
  db_data:

services:
  api:
    volumes:
      - ./app:/srv
    environment:
      - FLASK_DEBUG=1
      - PYTHON_ENV=development

  db:
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  front:
    environment:
      - NODE_ENV=development
      - http_proxy
      - https_proxy
    volumes:
      - ./front:/srv
    command: npm start

  web:
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./front/dist:/public/onikuflow
    ports:
      - "80:80"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

