version: '3.4'

services:
  app:
    build: 
      context: ./app
      args:
        - http_proxy
        - https_proxy
    command: flask run --host=0.0.0.0
    restart: on-failure
    logging:
      options:
        max-size: "200k"
        max-file: "10"


