version: '3.4'

services:
  db:
    image: h4nyu/mlboard_db
    build: 
      context: ./db
      args:
        - http_proxy
        - https_proxy
    restart: on-failure

  api:
    image: h4nyu/mlboard_api
    build: 
      context: ./api
      args:
        - http_proxy
        - https_proxy
    command: flask run --host=0.0.0.0
    restart: on-failure
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - db

  client:
    image: h4nyu/mlboard_client
    build: 
      context: ./client
      args:
        - http_proxy
        - https_proxy

  migration:
    image: h4nyu/mlboard_migration
    build: 
      context: ./migration
      args:
        - http_proxy
        - https_proxy
    restart: on-failure
    depends_on:
      - db

  board:
    image: h4nyu/mlboard_board
    build: 
      context: ./board
      args:
        - http_proxy
        - https_proxy
    restart: on-failure
    logging:
      options:
        max-size: "200k"
        max-file: "10"

  web:
    image: h4nyu/mlboard_web
    build: 
      context: ./web
      args:
        - http_proxy
        - https_proxy
    depends_on:
      - api
      - board
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
