version: '3.4'

services:
  api:
    build: 
      context: ./app
      args:
        - http_proxy
        - https_proxy
    command: flask run --host=0.0.0.0
    restart: on-failure
    logging:
      options:
        max-size: "200k"
        max-file: "10"

  front:
    build: 
      context: ./front
      args:
        - http_proxy
        - https_proxy
    restart: on-failure
    logging:
      options:
        max-size: "200k"
        max-file: "10"

  web:
    build: 
      context: ./web
      args:
        - http_proxy
        - https_proxy
    depends_on:
      - api
      - front
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
