version: '3.4'

volumes: 
  db_data:

services:
  db:
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    volumes:
      - ./api:/srv
    environment:
      - FLASK_DEBUG=1
      - PYTHON_ENV=development

  client:
    volumes:
      - ./client:/srv

  migration:
    volumes:
      - ./migration:/srv

  board:
    environment:
      - NODE_ENV=development
      - http_proxy
      - https_proxy
    volumes:
      - ./board:/srv
    command: npm start

  web:
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./front/dist:/public/
    ports:
      - "80:80"
