version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            docker-compose -v

      - run:
          name: Build Docker Images
          command: |
            docker-compose -f ./docker-compose.yml build

  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Test Migration
          command: |
            docker-compose -f ./docker-compose.yml up migration

      - run:
          name: Test Api
          command: |
            docker-compose -f ./docker-compose.yml run --rm api pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
